baseURL = "https://vnovel.pages.dev"
title = "VNovel"
author = ""
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "vnovel"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "G-1234567890"

# Disqus Comment System
#disqusShortname = ""

[params]
# The number of articles to be displayed on a single page.
paginator_pages = "6"

# Site logo.
#logo = ""

  [params.homepage_meta_tags]
    meta_description = "Pixiv-like theme for novels."
    meta_og_title = "VNovel"
    meta_og_type = "website"
    meta_og_url = "https://vnovel.pages.dev"
    meta_og_image = "https://vnovel.pages.dev/img/thumbnail.png"
    meta_og_description = "Pixiv-like theme for novels."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

# If you're using Yandex.Metrica, you can enable this feature.
#[params.analytics.yandexmetrica]
#    enabled = true
#    tagNumber = ''
