baseURL = "https://vnovel.pages.dev"
title = "VNovel"
author = ""
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "vnovel"
enableRobotsTXT = true
ignoreLogs = ['warning-goldmark-raw-html']

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

[taxonomies]
  tag = "tags"
  author = "authors"

[services]
  [services.googleAnalytics]
  # If you're using Google Analytics, you can enable this feature.
  #id = "G-1234567890"

  [services.disqus]
  # Disqus Comment System
  #shortname = "your-disqus-shortname"

[params]
# The number of articles to be displayed on a single page.
paginator_pages = "6"

# Site logo.
#logo = ""

  [params.homepage_meta_tags]
  meta_description = "Pixiv-like theme for novels."
  meta_og_title = "VNovel"
  meta_og_type = "website"
  meta_og_url = "https://vnovel.pages.dev"
  meta_og_image = "https://vnovel.pages.dev/img/thumbnail.png"
  meta_og_description = "Pixiv-like theme for novels."
  meta_twitter_card = "summary_large_image"
  meta_twitter_site = "@username"
  meta_twitter_creator = "@username"

  [params.giscus]
  # Giscus Comment System
  # See https://giscus.app for setup instructions
  #repo = "your-repo"
  #repo_id = "your-repo-id"
  #category = "Announcements"
  #category_id = "your-category-id"
  #mapping = "pathname"
  #strict = "0"
  #reactions_enabled = "1"
  #emit_metadata = "0"
  #input_position = "bottom"
  #theme = "preferred_color_scheme"
  #lang = "en"
  #loading = "lazy"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
